import { GPU, GPUPricing, ModelRequirement } from './types'

export const consumerGPUs: GPU[] = [
  {
    id: 'rtx-3060',
    name: 'RTX 3060',
    vendor: 'nvidia',
    category: 'consumer',
    vram: 12,
    vramType: 'GDDR6',
    bandwidth: 360,
    tflops_fp16: 12.7,
    tdp: 170,
    releaseYear: 2021,
    msrp: 329,
    architecture: 'Ampere',
  },
  {
    id: 'rtx-3070',
    name: 'RTX 3070',
    vendor: 'nvidia',
    category: 'consumer',
    vram: 8,
    vramType: 'GDDR6',
    bandwidth: 448,
    tflops_fp16: 22.1,
    tdp: 220,
    releaseYear: 2020,
    msrp: 499,
    architecture: 'Ampere',
  },
  {
    id: 'rtx-3080',
    name: 'RTX 3080',
    vendor: 'nvidia',
    category: 'consumer',
    vram: 10,
    vramType: 'GDDR6X',
    bandwidth: 760,
    tflops_fp16: 34.1,
    tdp: 320,
    releaseYear: 2020,
    msrp: 699,
    architecture: 'Ampere',
  },
  {
    id: 'rtx-3090',
    name: 'RTX 3090',
    vendor: 'nvidia',
    category: 'consumer',
    vram: 24,
    vramType: 'GDDR6X',
    bandwidth: 936,
    tflops_fp16: 71.1,
    tdp: 350,
    releaseYear: 2020,
    msrp: 1499,
    architecture: 'Ampere',
    nvlink: 'Gen3',
    multiGpu: true,
  },
  {
    id: 'rtx-4060',
    name: 'RTX 4060',
    vendor: 'nvidia',
    category: 'consumer',
    vram: 8,
    vramType: 'GDDR6',
    bandwidth: 272,
    tflops_fp16: 15.1,
    tdp: 115,
    releaseYear: 2023,
    msrp: 299,
    architecture: 'Ada Lovelace',
  },
  {
    id: 'rtx-4070',
    name: 'RTX 4070',
    vendor: 'nvidia',
    category: 'consumer',
    vram: 12,
    vramType: 'GDDR6X',
    bandwidth: 504,
    tflops_fp16: 29.1,
    tdp: 200,
    releaseYear: 2023,
    msrp: 599,
    architecture: 'Ada Lovelace',
  },
  {
    id: 'rtx-4070ti',
    name: 'RTX 4070 Ti',
    vendor: 'nvidia',
    category: 'consumer',
    vram: 12,
    vramType: 'GDDR6X',
    bandwidth: 504,
    tflops_fp16: 44.1,
    tdp: 285,
    releaseYear: 2023,
    msrp: 799,
    architecture: 'Ada Lovelace',
  },
  {
    id: 'rtx-4080',
    name: 'RTX 4080',
    vendor: 'nvidia',
    category: 'consumer',
    vram: 16,
    vramType: 'GDDR6X',
    bandwidth: 717,
    tflops_fp16: 64.6,
    tdp: 320,
    releaseYear: 2022,
    msrp: 1199,
    architecture: 'Ada Lovelace',
  },
  {
    id: 'rtx-4090',
    name: 'RTX 4090',
    vendor: 'nvidia',
    category: 'consumer',
    vram: 24,
    vramType: 'GDDR6X',
    bandwidth: 1008,
    tflops_fp16: 82.6,
    tdp: 450,
    releaseYear: 2022,
    msrp: 1599,
    architecture: 'Ada Lovelace',
  },
  {
    id: 'rtx-5090',
    name: 'RTX 5090',
    vendor: 'nvidia',
    category: 'consumer',
    vram: 32,
    vramType: 'GDDR7',
    bandwidth: 1792,
    tflops_fp16: 167,
    tdp: 575,
    releaseYear: 2025,
    msrp: 1999,
    architecture: 'Blackwell',
  },
]

export const datacenterGPUs: GPU[] = [
  {
    id: 'a100-40gb',
    name: 'A100 40GB',
    vendor: 'nvidia',
    category: 'datacenter',
    vram: 40,
    vramType: 'HBM2e',
    bandwidth: 1550,
    tflops_fp16: 312,
    tdp: 400,
    releaseYear: 2020,
    msrp: 10000,
    architecture: 'Ampere',
    nvlink: 'Gen3',
    multiGpu: true,
  },
  {
    id: 'a100-80gb',
    name: 'A100 80GB',
    vendor: 'nvidia',
    category: 'datacenter',
    vram: 80,
    vramType: 'HBM2e',
    bandwidth: 1940,
    tflops_fp16: 312,
    tdp: 400,
    releaseYear: 2020,
    msrp: 15000,
    architecture: 'Ampere',
    nvlink: 'Gen3',
    multiGpu: true,
  },
  {
    id: 'h100-pcie',
    name: 'H100 PCIe',
    vendor: 'nvidia',
    category: 'datacenter',
    vram: 80,
    vramType: 'HBM2e',
    bandwidth: 2000,
    tflops_fp16: 1513,
    tflops_fp8: 3026,
    tdp: 350,
    releaseYear: 2022,
    msrp: 30000,
    architecture: 'Hopper',
  },
  {
    id: 'h100-sxm',
    name: 'H100 SXM',
    vendor: 'nvidia',
    category: 'datacenter',
    vram: 80,
    vramType: 'HBM3',
    bandwidth: 3350,
    tflops_fp16: 1979,
    tflops_fp8: 3958,
    tdp: 700,
    releaseYear: 2022,
    msrp: 35000,
    architecture: 'Hopper',
    nvlink: 'Gen4',
    multiGpu: true,
  },
  {
    id: 'h200',
    name: 'H200',
    vendor: 'nvidia',
    category: 'datacenter',
    vram: 141,
    vramType: 'HBM3e',
    bandwidth: 4800,
    tflops_fp16: 1979,
    tflops_fp8: 3958,
    tdp: 700,
    releaseYear: 2024,
    msrp: 40000,
    architecture: 'Hopper',
    nvlink: 'Gen4',
    multiGpu: true,
  },
  {
    id: 'b200',
    name: 'B200',
    vendor: 'nvidia',
    category: 'datacenter',
    vram: 192,
    vramType: 'HBM3e',
    bandwidth: 8000,
    tflops_fp16: 4500,
    tflops_fp8: 9000,
    tdp: 1000,
    releaseYear: 2025,
    msrp: 50000,
    architecture: 'Blackwell',
    nvlink: 'Gen5',
    multiGpu: true,
  },
]

export const mockPricing: GPUPricing[] = [
  // Consumer GPUs
  { gpuId: 'rtx-3060', provider: 'vast', pricePerHour: 0.03, spotPrice: 0.015, availability: 'high', location: 'US-East', lastUpdated: new Date() },
  { gpuId: 'rtx-3060', provider: 'runpod', pricePerHour: 0.15, availability: 'high', location: 'US-West', lastUpdated: new Date() },
  { gpuId: 'rtx-3090', provider: 'vast', pricePerHour: 0.20, spotPrice: 0.10, availability: 'high', location: 'EU-West', lastUpdated: new Date() },
  { gpuId: 'rtx-3090', provider: 'runpod', pricePerHour: 0.40, availability: 'medium', location: 'US-East', lastUpdated: new Date() },
  { gpuId: 'rtx-4090', provider: 'vast', pricePerHour: 0.60, spotPrice: 0.35, availability: 'medium', location: 'US-West', lastUpdated: new Date() },
  { gpuId: 'rtx-4090', provider: 'runpod', pricePerHour: 0.79, availability: 'medium', location: 'EU-West', lastUpdated: new Date() },
  { gpuId: 'rtx-5090', provider: 'vast', pricePerHour: 1.20, spotPrice: 0.70, availability: 'low', location: 'US-East', lastUpdated: new Date() },
  { gpuId: 'rtx-5090', provider: 'runpod', pricePerHour: 1.49, availability: 'low', location: 'US-West', lastUpdated: new Date() },

  // Datacenter GPUs
  { gpuId: 'a100-40gb', provider: 'vast', pricePerHour: 0.52, spotPrice: 0.35, availability: 'high', location: 'US-East', lastUpdated: new Date() },
  { gpuId: 'a100-40gb', provider: 'runpod', pricePerHour: 0.60, availability: 'high', location: 'US-West', lastUpdated: new Date() },
  { gpuId: 'a100-40gb', provider: 'aws', pricePerHour: 1.89, availability: 'high', location: 'us-east-1', lastUpdated: new Date() },
  { gpuId: 'a100-80gb', provider: 'vast', pricePerHour: 0.80, spotPrice: 0.50, availability: 'medium', location: 'EU-West', lastUpdated: new Date() },
  { gpuId: 'a100-80gb', provider: 'runpod', pricePerHour: 1.19, availability: 'medium', location: 'US-East', lastUpdated: new Date() },
  { gpuId: 'a100-80gb', provider: 'aws', pricePerHour: 3.20, availability: 'medium', location: 'us-east-1', lastUpdated: new Date() },
  { gpuId: 'h100-pcie', provider: 'vast', pricePerHour: 1.50, spotPrice: 0.90, availability: 'low', location: 'US-West', lastUpdated: new Date() },
  { gpuId: 'h100-pcie', provider: 'runpod', pricePerHour: 1.89, availability: 'low', location: 'EU-West', lastUpdated: new Date() },
  { gpuId: 'h100-pcie', provider: 'aws', pricePerHour: 4.50, availability: 'medium', location: 'us-east-1', lastUpdated: new Date() },
  { gpuId: 'h100-sxm', provider: 'vast', pricePerHour: 2.10, spotPrice: 1.30, availability: 'low', location: 'US-East', lastUpdated: new Date() },
  { gpuId: 'h100-sxm', provider: 'runpod', pricePerHour: 2.69, availability: 'low', location: 'US-West', lastUpdated: new Date() },
  { gpuId: 'h100-sxm', provider: 'aws', pricePerHour: 6.50, availability: 'low', location: 'us-east-1', lastUpdated: new Date() },
  { gpuId: 'h200', provider: 'vast', pricePerHour: 3.20, spotPrice: 2.00, availability: 'low', location: 'US-East', lastUpdated: new Date() },
  { gpuId: 'h200', provider: 'runpod', pricePerHour: 3.99, availability: 'low', location: 'US-West', lastUpdated: new Date() },
  { gpuId: 'h200', provider: 'aws', pricePerHour: 8.00, availability: 'low', location: 'us-east-1', lastUpdated: new Date() },
  { gpuId: 'b200', provider: 'vast', pricePerHour: 4.50, spotPrice: 3.00, availability: 'low', location: 'US-West', lastUpdated: new Date() },
  { gpuId: 'b200', provider: 'runpod', pricePerHour: 5.49, availability: 'low', location: 'US-East', lastUpdated: new Date() },
  { gpuId: 'b200', provider: 'aws', pricePerHour: 12.00, availability: 'low', location: 'us-east-1', lastUpdated: new Date() },
]

export const modelRequirements: ModelRequirement[] = [
  { name: 'Phi-3 Mini', parameters: '3.8B', vram_fp16: 8, vram_int4: 2, minGPU: 'RTX 3060', recommendedGPU: 'RTX 4060' },
  { name: 'Llama 3.1 8B', parameters: '8B', vram_fp16: 16, vram_int4: 4, minGPU: 'RTX 3090', recommendedGPU: 'RTX 4070' },
  { name: 'Mistral 7B', parameters: '7B', vram_fp16: 14, vram_int4: 3.5, minGPU: 'RTX 3090', recommendedGPU: 'RTX 4070' },
  { name: 'Mixtral 8x7B', parameters: '47B', vram_fp16: 94, vram_int4: 24, minGPU: 'A100 80GB', recommendedGPU: 'H100 80GB' },
  { name: 'Llama 3.1 70B', parameters: '70B', vram_fp16: 140, vram_int4: 35, minGPU: 'A100 80GB x2', recommendedGPU: 'H100 80GB' },
  { name: 'Llama 3.1 405B', parameters: '405B', vram_fp16: 810, vram_int4: 203, minGPU: 'H200 x8', recommendedGPU: 'B200 x4' },
]
